--- 
pid: tmp/pids/thin.pid
adapter: rails
log: log/thin.log
port: 42246
timeout: 30
max_conns: 1024
max_persistent_conns: 512
chdir: /var/www/nscl
environment: production
daemonize: true
address: 0.0.0.0
require: []

